version: '2.14.0'

services:
  # order-svc:
  #   image: 'ayesh/order-svc:0.0.1'
  #   depends_on: 
  #     inventory-svc: 
  #         condition: service_started
  #     mysql: 
  #         condition: service_healthy
  #   network_mode: "host"

  # inventory-svc:
  #   image: 'ayesh/inventory-svc:0.0.1'
  #   network_mode: "host"

  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=order_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"